[package]
name = "openmls_rust_crypto"
authors = ["OpenMLS Authors"]
version = "0.3.0"
edition = "2021"
description = "A crypto backend for OpenMLS implementing openmls_traits using RustCrypto primitives."
license = "MIT"
documentation = "https://docs.rs/openmls_rust_crypto"
repository = "https://github.com/openmls/openmls/tree/main/openmls_rust_crypto"
readme = "README.md"

[dependencies]
openmls_traits = { version = "0.3.0", path = "../traits" }
openmls_memory_storage = { version = "0.3.0", path = "../memory_storage" }
hpke = { version = "0.2.0", package = "hpke-rs", default-features = false, features = [
  "hazmat",
  "serialization",
] }
# Rust Crypto dependencies
sha2 = { version = "0.10" }
aes-gcm = { version = "0.10" }
chacha20poly1305 = { version = "0.10" }
hmac = { version = "0.12" }
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
p256 = { version = "0.13" }
hkdf = { version = "0.12" }
rand = "0.8"
rand_chacha = { version = "0.3" }
hpke-rs-crypto = { version = "0.2.0" }
hpke-rs-rust-crypto = { version = "0.2.0" }
tls_codec = { workspace = true }
thiserror = "2.0"
serde = { version = "^1.0", features = ["derive"] }

[features]
test-utils = ["openmls_memory_storage/test-utils"]
