[package]
name = "mls-ds"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.0"
actix-web = "3"
futures-core = "0.3"
futures-util = "0.3"
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
serde = {version = "1.0", features = ["derive"]}
uuid = { version = "0.8", features = ["serde", "v4"] }
clap = "2.33"
base64 = "0.13"
tls_codec = "0.2.0"

openmls = {features = ["test-utils"], version = "0.4.0-pre.2" }
openmls_traits = "0.1.0-pre.2" 
openmls_rust_crypto = "0.1.0-pre.2"

ds-lib = { path = "../ds-lib/" }

[patch.crates-io]
openmls = { path = "../../openmls" }
openmls_traits = { path = "../../traits" }
openmls_rust_crypto = { path = "../../openmls_rust_crypto" }
openmls_memory_keystore = { path = "../../memory_keystore" }
