[package]
name = "openmls_traits"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/traits.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tls_codec = { version = "0.2.0-pre.2", features = ["derive", "serde_serialize"] }
