name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation:
    if: github.repository == 'openmls/openmls'
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@master
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      - name: Build docs
        run: |
          cd openmls
          RUSTDOCFLAGS="--cfg doc_cfg --cfg docsrs" cargo +nightly doc --all-features --no-deps
          touch ../target/doc/.nojekyll
          cd ..
          mkdir temp_docs
          mv target/doc temp_docs
          cd book
          mdbook build
          cd ..
          mv book/book temp_docs
          cd temp_docs
          cat > index.html <<EOF
          <!doctype html>
          <html>
          <a href="doc/openmls/index.html">Docs</a>
          <a href="book/index.html">Book</a>
          </html>
          EOF
      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: temp_docs
          cname: latest.openmls.tech
